version: '3.8'

services:
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
      POSTGRES_DB: temporal
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"

  temporal:
    image: temporalio/auto-setup:latest
    ports:
      - "7233:7233"
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
    depends_on:
      postgresql:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "tctl", "--address", "localhost:7233", "cluster", "health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  temporal-ui:
    image: temporalio/ui:latest
    ports:
      - "8233:8080"
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    depends_on:
      - temporal

  df-worker:
    build: .
    environment:
      TEMPORAL_ADDRESS: "temporal:7233"
    depends_on:
      - temporal
    volumes:
      - ./data:/app/data
    command: sh -c "sleep 30 && python3 run_workflow.py & python3 worker.py"
